# This file was generated by GoReleaser. DO NOT EDIT.
cask "fm" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "0203863e091e9d13f65463ca17b4b81a8b5075e5caf1569bcce8d6fa91e09c18"
      url "https://github.com/NoFuss-io/frontmatter/releases/download/v#{version}/fm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "68512369f009f818efc1b1a21d31ab3d97ab826803068c231bbd9938fcbc609e"
      url "https://github.com/NoFuss-io/frontmatter/releases/download/v#{version}/fm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8dad21dc457242602b6c5221728b87ccb9a9230234aa6e86ca7c2681ba03450b"
      url "https://github.com/NoFuss-io/frontmatter/releases/download/v#{version}/fm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9e1b628740fef8b86154c4b5066c4252d13dbaa39f8870799c9f2fad58d26c0c"
      url "https://github.com/NoFuss-io/frontmatter/releases/download/v#{version}/fm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fm"
  desc "Markdown frontmatter batch editor with an SQL-style DSL."
  homepage "https://github.com/NoFuss-io/frontmatter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fm"
  manpage "docs/man/fm.1"
  bash_completion "completions/fm.bash"
  fish_completion "completions/fm.fish"
  zsh_completion "completions/fm.zsh"

  # No zap stanza required

end
