# This file was generated by GoReleaser. DO NOT EDIT.
cask "fm" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "f6257f81a230fc02159e207b04f53ba2909a9944db49d6fff71dc1ccd706d2db"
      url "https://github.com/NoFuss-io/frontmatter/releases/download/v#{version}/fm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "10021888bea9328c1ac42c43c794e028949fe360f8ca9da37369782611396439"
      url "https://github.com/NoFuss-io/frontmatter/releases/download/v#{version}/fm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "731c4185c43f18bee458066ff981b8aa67c5f212fd837c9acc33ebd760d57e49"
      url "https://github.com/NoFuss-io/frontmatter/releases/download/v#{version}/fm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "55cef13d72213d28d34bc646cf750ed93a540c4b07cef51e374ffe07eee90d1a"
      url "https://github.com/NoFuss-io/frontmatter/releases/download/v#{version}/fm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fm"
  desc "Markdown frontmatter batch editor with an SQL-style DSL."
  homepage "https://github.com/NoFuss-io/frontmatter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fm"
  manpage "docs/man/fm.1"
  bash_completion "completions/fm.bash"
  fish_completion "completions/fm.fish"
  zsh_completion "completions/fm.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fm"]
    end
  end

  # No zap stanza required

end
