# This file was generated by GoReleaser. DO NOT EDIT.
cask "fm" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "0bc1fb4d30c027d4515d66f681ee38a6d04e6cb4a2814232eb1cae63e3e9df0d"
      url "https://github.com/NoFuss-io/frontmatter/releases/download/v#{version}/fm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c24cd51dd10b23b80e7857243f4522e0db7b2c8c0708dbbdc3a8c31dc89bc4c"
      url "https://github.com/NoFuss-io/frontmatter/releases/download/v#{version}/fm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2cee1630281e6b49699eb17103303cb37f10d094007fec2b92ea21e800dee896"
      url "https://github.com/NoFuss-io/frontmatter/releases/download/v#{version}/fm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ee65548137502dcea229484785b5a58c6123c0faeb598ab635c49fd059c0fc75"
      url "https://github.com/NoFuss-io/frontmatter/releases/download/v#{version}/fm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fm"
  desc "Markdown frontmatter batch editor with an SQL-style DSL."
  homepage "https://github.com/NoFuss-io/frontmatter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fm"
  manpage "docs/man/fm.1"
  bash_completion "completions/fm.bash"
  fish_completion "completions/fm.fish"
  zsh_completion "completions/fm.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fm"]
    end
  end

  # No zap stanza required

end
